//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public int maHDB { get; set; }
        public string tk { get; set; }
        public string ten { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
        public string ngaytao { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
