//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonMua
    {
        public int maHDM { get; set; }
        public string san_pham { get; set; }
        public string don_gia { get; set; }
        public Nullable<double> so_luong { get; set; }
        public Nullable<int> maNCC { get; set; }
        public string tk { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
