//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int maKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string tk { get; set; }
        public Nullable<double> tongtiendamua { get; set; }
        public Nullable<bool> loaiKH { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
