//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int maNV { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string gmail { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string tk { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
